---
title: "Heidi Kloser Homework_5"
author: "Heidi Kloser"
date: "2022-11-15"
output: pdf_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, 
                      error = FALSE)
```


Libraries
```{r}
#packages
library(tidyverse)
library(lubridate)
library(ggthemes)
library(broom)
library(knitr)
library(scales)
library(tigris)
library(sf)
library(viridis)
library(shiny)
library(leaflet)
library(DT)
library(plotly)
library(flexdashboard)
library(jsonlite)
library(maptools)
library(ggplot2)
```

List files in "data" sub directory
```{r}
list.files("data")
```

```{r}
# read in data
homicides<-read.csv("data/homicide-data.csv")
```

Putting map components in 
```{r}
ga_counties <- counties(state = "GA", cb = TRUE, class = "sf")
#getting geographical data from sf/tigris
class(ga_counties)
```

checking county and class data
```{r}
ga_counties %>% 
  slice(1:3)
class(ga_counties$geometry)
```

Incorporating homicide data into map
```{r}
atlanta <- tracts(state = "GA", county = "Fulton", cb = TRUE, class = "sf")
class(atlanta)
```

checking tract and class data
```{r}
atlanta %>% 
  slice(1:3)
class(atlanta$geometry)

ga_f <- county_subdivisions(state = "GA", county = "Fulton", cb = TRUE, class = "sf")
```
Entering and cleaning data for the homicides
```{r}
# piping n code to clean up data
homicides<- homicides%>%
  mutate(state = str_to_upper(string = state))%>% # changing case
  mutate(city_name = paste(city, state))%>% # combine city and state name to one col
    mutate(status = factor(disposition, levels = c("Closed by arrest", 
                                                      "Closed without arrest", 
                                                      "Open/No arrest"), 
                      labels = c("Solved", "Unsolved", "Unsolved")))%>% 
  # creating new col for solves/unsolved
  filter(str_detect(city_name, "Atlanta"))%>% # filtering to only Atlanta
  select(- city, - state, - disposition) %>% #removing redundant columns
  dplyr::mutate(victim_race = forcats::fct_lump(victim_race, n = 3))


head(homicides, 3)
```

Change to an sf object by saying which columns are the coordinates and setting a CRS:
```{r}
at_hom <- st_as_sf(homicides, coords = c("lon", "lat")) %>%
st_set_crs(4269) #setting CRS
at_hom %>% slice(1:3)
```
Map
```{r}
#trying to put points on the map
ggplot() + 
  geom_sf(data = ga_f)+ 
  theme(axis.text.x = element_text(angle = 45))+
  xlim(c(-84.73, -84.3)) + ylim(c(33.6, 34.0))+
  facet_wrap(~status, ncol = 2)+
  geom_sf(data = at_hom, aes(color = victim_race))+
  ggtitle("Solved vs. Unsolved Homicides in Atlanta by Race")+
  labs(color = "Victim Race")+
  theme_few()
```